package com.regmold.codegen;

import com.regmold.model.*;

import java.util.ArrayList;
import java.util.List;

import static com.regmold.codegen.Codegen.*;

/** Deterministic C access layer. All symbols derive from the canonical model only. */
public class CGenerator {

    private final ChipModel m;
    private final String version;
    private final String fp;
    private final String trace;

    public CGenerator(ChipModel m, String version, String fp) {
        this.m = m;
        this.version = version;
        this.fp = fp;
        this.trace = trace(m, version, fp);
    }

    private String u(String reg) { return "REGMOLD_" + upper(reg); }
    private String f(String reg, String field) { return "REGMOLD_" + upper(reg) + "_" + upper(field); }
    private String fn(String reg) { return "regmold_" + lower(reg); }

    public String header() {
        StringBuilder sb = new StringBuilder();
        String guard = "REGMOLD_" + upper(m.name()) + "_H";
        sb.append("/* Generated by regmold. Do not edit. */\n");
        sb.append("/* model: ").append(m.name()).append(" revision: ").append(version).append(" */\n");
        sb.append("/* fingerprint: ").append(fp).append(" */\n");
        sb.append("#ifndef ").append(guard).append("\n#define ").append(guard).append("\n\n");
        sb.append("#include <stdint.h>\n\n");
        sb.append("#define REGMOLD_MODEL_REVISION \"").append(version).append("\"\n");
        sb.append("#define REGMOLD_MODEL_FINGERPRINT \"").append(fp).append("\"\n");
        sb.append("extern const char *const regmold_model_revision;\n");
        sb.append("extern const char *const regmold_model_fingerprint;\n\n");
        for (RegisterDef r : m.registers()) emitRegister(sb, r);
        sb.append("#endif /* ").append(guard).append(" */\n");
        return sb.toString();
    }

    private void emitRegister(StringBuilder sb, RegisterDef r) {
        sb.append("/* ---- ").append(r.name());
        if (r.isAlias()) sb.append(" (alias of ").append(r.aliasOf()).append(", semantic ").append(r.semantic()).append(")");
        sb.append(" @ 0x").append(hex(r.address())).append(" width ").append(r.width());
        sb.append(" reset 0x").append(hex(r.reset())).append(" */\n");
        def(sb, u(r.name()) + "_ADDR", hex(r.address()) + "u");
        def(sb, u(r.name()) + "_RESET", hex(r.reset()) + "ull");
        if (r.words() > 1) def(sb, u(r.name()) + "_WORDS", String.valueOf(r.words()) + "u");
        long reserved = 0, writable = 0;
        for (BitField fl : r.fields()) {
            def(sb, f(r.name(), fl.name()) + "_MASK", hex(fl.mask()) + "ull");
            def(sb, f(r.name(), fl.name()) + "_OFFSET", fl.offset() + "u");
            def(sb, f(r.name(), fl.name()) + "_WIDTH", fl.width() + "u");
            if (fl.reset() != null) def(sb, f(r.name(), fl.name()) + "_RESET", hex(fl.reset()) + "ull");
            if (fl.access() == AccessType.RESERVED) reserved |= fl.mask();
            else if (fl.access() != AccessType.RO && fl.access() != AccessType.RC) writable |= fl.mask();
            if (!fl.sideEffects().isEmpty()) {
                StringBuilder fx = new StringBuilder();
                for (SideEffect se : fl.sideEffects()) fx.append(se.action()).append(' ').append(se.targetKey()).append("; ");
                sb.append("/* side-effects of ").append(r.name()).append('.').append(fl.name())
                  .append(": ").append(fx).append(trace).append(" */\n");
            }
        }
        def(sb, u(r.name()) + "_RESERVED_MASK", hex(reserved) + "ull");
        def(sb, u(r.name()) + "_WRITABLE_MASK", hex(writable) + "ull");
        if (r.lockedBy() != null) {
            LockSpec lk = r.lockedBy();
            def(sb, u(r.name()) + "_LOCK_REG", "\"" + lk.register() + "\"");
            def(sb, u(r.name()) + "_LOCK_OPEN", lk.openValue() + "ull");
        }
        emitFunctions(sb, r, reserved);
        sb.append('\n');
    }

    private void def(StringBuilder sb, String name, String value) {
        sb.append("#define ").append(pad(name, 44)).append(value)
          .append(" /* ").append(trace).append(" */\n");
    }

    private static String pad(String s, int n) {
        return s.length() >= n ? s + " " : s + " ".repeat(n - s.length());
    }

    private void emitFunctions(StringBuilder sb, RegisterDef r, long reserved) {
        String t = r.width() > 32 ? "uint64_t" : "uint32_t";
        if (r.isAlias()) {
            sb.append("/* ").append(trace).append(" */\n");
            sb.append("static inline void ").append(fn(r.name())).append("_write(uintptr_t base, ").append(t).append(" v) {\n");
            emitStoreWords(sb, r, "v");
            sb.append("}\n");
            return;
        }
        sb.append("/* ").append(trace).append(" */\n");
        sb.append("static inline ").append(t).append(' ').append(fn(r.name())).append("_read(uintptr_t base) {\n");
        emitLoadWords(sb, r);
        sb.append("}\n");
        if (r.words() > 1) {
            sb.append("/* ").append(trace).append(" */\n");
            sb.append("static inline void ").append(fn(r.name())).append("_read_words(uintptr_t base, uint32_t out[")
              .append(r.words()).append("]) {\n");
            for (int w : wordOrder(r)) {
                sb.append("    out[").append(w).append("] = *(volatile const uint32_t *)(base + ")
                  .append(u(r.name())).append("_ADDR + ").append(w * 4).append("u);\n");
            }
            sb.append("}\n");
        }
        sb.append("/* ").append(trace).append(" */\n");
        sb.append("static inline void ").append(fn(r.name())).append("_write(uintptr_t base, ").append(t).append(" v) {\n");
        sb.append("    ").append(t).append(" cur = ").append(fn(r.name())).append("_read(base);\n");
        sb.append("    v = (cur & ").append(u(r.name())).append("_RESERVED_MASK) | (v & ")
          .append(u(r.name())).append("_WRITABLE_MASK);\n");
        emitStoreWords(sb, r, "v");
        sb.append("}\n");
        for (BitField fl : r.fields()) {
            String fbase = fn(r.name()) + "_" + lower(fl.name());
            String mask = f(r.name(), fl.name()) + "_MASK";
            String off = f(r.name(), fl.name()) + "_OFFSET";
            switch (fl.access()) {
                case RW -> {
                    sb.append("/* ").append(trace).append(" */\n");
                    sb.append("static inline void ").append(fbase).append("_modify(uintptr_t base, ").append(t).append(" v) {\n");
                    sb.append("    ").append(t).append(" cur = ").append(fn(r.name())).append("_read(base);\n");
                    sb.append("    cur = (cur & ~(").append(mask).append(")) | ((v << ").append(off).append(") & ").append(mask).append(");\n");
                    emitStoreWords(sb, r, "cur");
                    sb.append("}\n");
                }
                case W1C -> {
                    sb.append("/* ").append(trace).append(" */\n");
                    sb.append("static inline void ").append(fbase).append("_clear(uintptr_t base) {\n");
                    emitStoreWords(sb, r, mask);
                    sb.append("}\n");
                }
                case W1S -> {
                    sb.append("/* ").append(trace).append(" */\n");
                    sb.append("static inline void ").append(fbase).append("_set(uintptr_t base) {\n");
                    emitStoreWords(sb, r, mask);
                    sb.append("}\n");
                }
                case RC -> {
                    sb.append("/* ").append(trace).append(" */\n");
                    sb.append("static inline ").append(t).append(' ').append(fbase).append("_read(uintptr_t base) {\n");
                    sb.append("    return (").append(fn(r.name())).append("_read(base) & ").append(mask).append(") >> ").append(off).append(";\n");
                    sb.append("}\n");
                }
                default -> { }
            }
        }
    }

    private void emitLoadWords(StringBuilder sb, RegisterDef r) {
        if (r.words() == 1) {
            sb.append("    return *(volatile const uint32_t *)(base + ").append(u(r.name())).append("_ADDR);\n");
            return;
        }
        sb.append("    uint64_t v = 0;\n");
        for (int w : wordOrder(r)) {
            sb.append("    v |= (uint64_t)*(volatile const uint32_t *)(base + ").append(u(r.name()))
              .append("_ADDR + ").append(w * 4).append("u) << ").append(w * 32).append(";\n");
        }
        sb.append("    return v;\n");
    }

    private void emitStoreWords(StringBuilder sb, RegisterDef r, String expr) {
        for (int w : wordOrder(r)) {
            sb.append("    *(volatile uint32_t *)(base + ").append(u(r.name())).append("_ADDR + ")
              .append(w * 4).append("u) = (uint32_t)((").append(expr).append(") >> ").append(w * 32).append(");\n");
        }
    }

    private int[] wordOrder(RegisterDef r) {
        int n = r.words();
        int[] order = new int[n];
        for (int i = 0; i < n; i++) order[i] = "hi-first".equals(r.wordOrder()) ? n - 1 - i : i;
        return order;
    }

    public String source() {
        String chip = sanitize(m.name());
        return "/* Generated by regmold. Do not edit. */\n/* " + trace + " */\n" +
                "#include \"regmold_" + chip + ".h\"\n\n" +
                "const char *const regmold_model_revision = REGMOLD_MODEL_REVISION;\n" +
                "const char *const regmold_model_fingerprint = REGMOLD_MODEL_FINGERPRINT;\n";
    }

    private static String hex(long v) {
        return "0x" + Long.toHexString(v);
    }
}
