package com.regmold.codegen;

import com.regmold.model.*;

import static com.regmold.codegen.Codegen.*;

/** Deterministic Rust access layer (no_std compatible, core::ptr only). */
public class RustGenerator {

    private final ChipModel m;
    private final String version;
    private final String fp;
    private final String trace;

    public RustGenerator(ChipModel m, String version, String fp) {
        this.m = m;
        this.version = version;
        this.fp = fp;
        this.trace = trace(m, version, fp);
    }

    private String c(String reg) { return upper(reg); }
    private String c(String reg, String field) { return upper(reg) + "_" + upper(field); }
    private String fn(String reg) { return lower(reg); }

    public String source() {
        StringBuilder sb = new StringBuilder();
        sb.append("//! Generated by regmold. Do not edit.\n");
        sb.append("//! model: ").append(m.name()).append(" revision: ").append(version).append('\n');
        sb.append("//! fingerprint: ").append(fp).append('\n');
        sb.append("#![allow(dead_code)]\n\n");
        sb.append("pub const REGMOLD_MODEL_REVISION: &str = \"").append(version).append("\";\n");
        sb.append("pub const REGMOLD_MODEL_FINGERPRINT: &str = \"").append(fp).append("\";\n\n");
        for (RegisterDef r : m.registers()) emitRegister(sb, r);
        return sb.toString();
    }

    private void emitRegister(StringBuilder sb, RegisterDef r) {
        sb.append("// ").append(r.name());
        if (r.isAlias()) sb.append(" (alias of ").append(r.aliasOf()).append(", semantic ").append(r.semantic()).append(")");
        sb.append(" @ 0x").append(Long.toHexString(r.address())).append(" width ").append(r.width()).append('\n');
        konst(sb, c(r.name()) + "_ADDR", "usize", hex(r.address()));
        konst(sb, c(r.name()) + "_RESET", "u64", hex(r.reset()));
        String t = r.width() > 32 ? "u64" : "u32";
        long reserved = 0, writable = 0;
        for (BitField fl : r.fields()) {
            konst(sb, c(r.name(), fl.name()) + "_MASK", t, hex(fl.mask()));
            konst(sb, c(r.name(), fl.name()) + "_OFFSET", "u32", String.valueOf(fl.offset()));
            konst(sb, c(r.name(), fl.name()) + "_WIDTH", "u32", String.valueOf(fl.width()));
            if (fl.access() == AccessType.RESERVED) reserved |= fl.mask();
            else if (fl.access() != AccessType.RO && fl.access() != AccessType.RC) writable |= fl.mask();
        }
        konst(sb, c(r.name()) + "_RESERVED_MASK", t, hex(reserved));
        konst(sb, c(r.name()) + "_WRITABLE_MASK", t, hex(writable));
        emitFunctions(sb, r);
        sb.append('\n');
    }

    private void konst(StringBuilder sb, String name, String ty, String value) {
        sb.append("/// ").append(trace).append('\n');
        sb.append("pub const ").append(name).append(": ").append(ty).append(" = ").append(value);
        if ("u64".equals(ty) || "u32".equals(ty)) sb.append(ty);
        sb.append(";\n");
    }

    private void emitFunctions(StringBuilder sb, RegisterDef r) {
        String t = r.width() > 32 ? "u64" : "u32";
        String base = fn(r.name());
        String addr = c(r.name()) + "_ADDR";
        if (r.isAlias()) {
            doc(sb);
            sb.append("pub unsafe fn ").append(base).append("_write(base: *mut u32, v: ").append(t).append(") {\n");
            emitStoreWords(sb, r, "v");
            sb.append("}\n");
            return;
        }
        doc(sb);
        sb.append("pub unsafe fn ").append(base).append("_read(base: *mut u32) -> ").append(t).append(" {\n");
        if (r.words() == 1) {
            sb.append("    core::ptr::read_volatile(base.add(").append(addr).append(" / 4))\n");
        } else {
            sb.append("    let mut v: u64 = 0;\n");
            for (int w : wordOrder(r)) {
                sb.append("    v |= (core::ptr::read_volatile(base.add(").append(addr).append(" / 4 + ").append(w)
                  .append(")) as u64) << ").append(w * 32).append(";\n");
            }
            sb.append("    v\n");
        }
        sb.append("}\n");
        doc(sb);
        sb.append("pub unsafe fn ").append(base).append("_write(base: *mut u32, v: ").append(t).append(") {\n");
        sb.append("    let cur = ").append(base).append("_read(base);\n");
        sb.append("    let v = (cur & ").append(c(r.name())).append("_RESERVED_MASK) | (v & ")
          .append(c(r.name())).append("_WRITABLE_MASK);\n");
        emitStoreWords(sb, r, "v");
        sb.append("}\n");
        for (BitField fl : r.fields()) {
            String fb = base + "_" + lower(fl.name());
            String mask = c(r.name(), fl.name()) + "_MASK";
            String off = c(r.name(), fl.name()) + "_OFFSET";
            switch (fl.access()) {
                case RW -> {
                    doc(sb);
                    sb.append("pub unsafe fn ").append(fb).append("_modify(base: *mut u32, v: ").append(t).append(") {\n");
                    sb.append("    let cur = ").append(base).append("_read(base);\n");
                    sb.append("    let v = (cur & !").append(mask).append(") | ((v << ").append(off).append(") & ").append(mask).append(");\n");
                    emitStoreWords(sb, r, "v");
                    sb.append("}\n");
                }
                case W1C -> {
                    doc(sb);
                    sb.append("pub unsafe fn ").append(fb).append("_clear(base: *mut u32) {\n");
                    emitStoreWords(sb, r, mask);
                    sb.append("}\n");
                }
                case W1S -> {
                    doc(sb);
                    sb.append("pub unsafe fn ").append(fb).append("_set(base: *mut u32) {\n");
                    emitStoreWords(sb, r, mask);
                    sb.append("}\n");
                }
                case RC -> {
                    doc(sb);
                    sb.append("pub unsafe fn ").append(fb).append("_read(base: *mut u32) -> ").append(t).append(" {\n");
                    sb.append("    (").append(base).append("_read(base) & ").append(mask).append(") >> ").append(off).append('\n');
                    sb.append("}\n");
                }
                default -> { }
            }
        }
    }

    private void doc(StringBuilder sb) {
        sb.append("/// ").append(trace).append('\n');
    }

    private void emitStoreWords(StringBuilder sb, RegisterDef r, String expr) {
        String addr = c(r.name()) + "_ADDR";
        for (int w : wordOrder(r)) {
            sb.append("    core::ptr::write_volatile(base.add(").append(addr).append(" / 4 + ").append(w)
              .append("), ((").append(expr).append(") >> ").append(w * 32).append(") as u32);\n");
        }
    }

    private int[] wordOrder(RegisterDef r) {
        int n = r.words();
        int[] order = new int[n];
        for (int i = 0; i < n; i++) order[i] = "hi-first".equals(r.wordOrder()) ? n - 1 - i : i;
        return order;
    }

    private static String hex(long v) {
        return "0x" + Long.toHexString(v);
    }
}
