spring.application.name=register-forge
server.address=127.0.0.1
server.port=5244
spring.datasource.url=jdbc:sqlite:${regforge.db:regforge.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jackson.serialization.indent-output=true
